export const CATEGORIE_STANDARD = [
  "Utensili manuali",
  "Strumenti di misura",
  "Utensili a filo",
  "Utensili a batteria",
  "Accessori",
  "Portautensili",
  "Ferramenta",
  "Fissaggio",
  "Giardinaggio",
  "Vernici",
  "Idraulica",
  "Elettrico",
  "Antinfortunistica",
  "Auto",
  "Casa",
  "Chiavi",
  "Altro",
];
